# Generated by Django 5.2.4 on 2025-07-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_generatedimage_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedimage',
            old_name='resolution',
            new_name='height',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='url',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='width',
            field=models.IntegerField(default=512),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='style',
            field=models.IntegerField(default=0),
        ),
    ]
