# Generated by Django 5.2.4 on 2025-07-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_resolution_generatedimage_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToImageSDXL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('output_file', models.CharField(max_length=255)),
                ('image_strength', models.FloatField()),
                ('cfg_scale', models.FloatField()),
                ('steps', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
