# Generated by Django 5.2.4 on 2025-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imagetoimagesdxl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetoimagesdxl',
            name='cfg_scale',
            field=models.FloatField(blank=True, default=6, null=True),
        ),
        migrations.AlterField(
            model_name='imagetoimagesdxl',
            name='height',
            field=models.IntegerField(blank=True, default=3520, null=True),
        ),
        migrations.AlterField(
            model_name='imagetoimagesdxl',
            name='image_strength',
            field=models.FloatField(blank=True, default=0.35, null=True),
        ),
        migrations.AlterField(
            model_name='imagetoimagesdxl',
            name='output_file',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagetoimagesdxl',
            name='prompt',
            field=models.TextField(blank=True, default='extend the image downward, same style and colors', null=True),
        ),
        migrations.AlterField(
            model_name='imagetoimagesdxl',
            name='steps',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='imagetoimagesdxl',
            name='width',
            field=models.IntegerField(blank=True, default=1792, null=True),
        ),
    ]
