# Generated by Django 5.2.4 on 2025-07-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_imagetoimagesdxl_cfg_scale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpaintingSDXL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_file', models.CharField(blank=True, default='', help_text='Ścieżka do wygenerowanego obrazu', max_length=255, null=True)),
                ('left', models.IntegerField(default=0, help_text='Ile pikseli rozszerzyć w lewo')),
                ('right', models.IntegerField(default=0, help_text='Ile pikseli rozszerzyć w prawo')),
                ('up', models.IntegerField(default=0, help_text='Ile pikseli rozszerzyć w górę')),
                ('down', models.IntegerField(default=0, help_text='Ile pikseli rozszerzyć w dół')),
                ('output_format', models.CharField(default='png', help_text='Format wygenerowanego obrazu (np. webp, png)', max_length=10)),
                ('input_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outpaintings', to='api.generatedimage')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageToImageSDXL',
        ),
    ]
