# Generated by Django 5.2.4 on 2025-07-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_outpaintingsdxl_delete_imagetoimagesdxl'),
    ]

    operations = [
        migrations.CreateModel(
            name='upscaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_file', models.CharField(blank=True, default='', help_text='Ścieżka do wygenerowanego obrazu', max_length=255, null=True)),
                ('upscale_factor', models.IntegerField(default=2, help_text='Współczynnik skalowania obrazu (np. 2x, 4x)')),
                ('input_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upscalings', to='api.generatedimage')),
            ],
        ),
    ]
