# Generated by Django 5.2.4 on 2025-07-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_atmosfera_detale_inspiracja_kolorystyka_kompozycja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosfera',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detale',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspiracja',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kolorystyka',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kompozycja',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspektywa',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realizm',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stylartystyczny',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stylnarracyjny',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tlo',
            name='tlumaczenie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
