# Generated by Django 5.2.4 on 2025-07-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_atmosfera_tlumaczenie_detale_tlumaczenie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='style',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='atmosfera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.atmosfera'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='detale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.detale'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='inspiracja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inspiracja'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='kolorystyka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.kolorystyka'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='kompozycja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.kompozycja'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='perspektywa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.perspektywa'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='realizm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.realizm'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='styl_artystyczny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stylartystyczny'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='styl_narracyjny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stylnarracyjny'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='tlo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tlo'),
        ),
    ]
