# Generated by Django 5.2.4 on 2025-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_generatedimage_style_generatedimage_atmosfera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='url',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
