# Generated by Django 5.2.4 on 2025-07-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_calendartype_alter_generatedimage_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottom_type', models.CharField(choices=[('image', 'Image'), ('color', 'Color'), ('gradient', 'Gradient'), ('theme-gradient', 'Theme Gradient')], max_length=20)),
                ('bottom_color', models.CharField(blank=True, max_length=7, null=True)),
                ('gradient_start_color', models.CharField(blank=True, max_length=7, null=True)),
                ('gradient_end_color', models.CharField(blank=True, max_length=7, null=True)),
                ('gradient_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('gradient_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bottom_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_bottom_image', to='api.generatedimage')),
                ('top_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_top_image', to='api.generatedimage')),
            ],
        ),
    ]
