# Generated by Django 5.2.4 on 2025-08-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_calendar_field1_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='year_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='year_font',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='year_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='year_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='year_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='year_weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
