# Generated by Django 5.2.4 on 2025-08-19 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_calendar_year_color_calendar_year_font_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='bottom_color',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='bottom_image',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='bottom_type',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='gradient_direction',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='gradient_end_color',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='gradient_start_color',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='gradient_theme',
        ),
        migrations.AddField(
            model_name='calendar',
            name='bottom_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='bottom_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BottomColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=7)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BottomGradient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_color', models.CharField(max_length=7)),
                ('end_color', models.CharField(max_length=7)),
                ('direction', models.CharField(blank=True, max_length=20, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BottomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.generatedimage')),
            ],
        ),
    ]
