# Generated by Django 5.2.4 on 2025-08-31 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_calendar_bottom_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='year_color',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='year_font',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='year_position',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='year_size',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='year_text',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='year_weight',
        ),
        migrations.CreateModel(
            name='CalendarYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=255)),
                ('font', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='year_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_year_data', to='api.calendaryeardata'),
        ),
    ]
