# Generated by Django 5.2.4 on 2025-08-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_calendar_year_color_remove_calendar_year_font_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmonthfieldimage',
            old_name='position',
            new_name='positionX',
        ),
        migrations.RenameField(
            model_name='calendaryeardata',
            old_name='position',
            new_name='positionX',
        ),
        migrations.AddField(
            model_name='calendarmonthfieldimage',
            name='positionY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='calendaryeardata',
            name='positionY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
