# Generated by Django 5.2.4 on 2025-09-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_position_calendarmonthfieldimage_positionx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomgradient',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
