# Generated by Django 5.2.4 on 2025-09-22 23:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageForField',
        ),
    ]
