# Generated by Django 5.2.4 on 2025-10-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_image_imageforfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(default='new calendar', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='name',
            field=models.CharField(default='new_image', max_length=100),
        ),
    ]
