# Generated by Django 5.2.4 on 2025-10-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendaryeardata',
            old_name='positionX',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='calendaryeardata',
            name='positionY',
        ),
    ]
