# Generated by Django 5.2.4 on 2025-11-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_positionx_calendaryeardata_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendaryeardata',
            old_name='position',
            new_name='positionX',
        ),
        migrations.AddField(
            model_name='calendaryeardata',
            name='positionY',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
