# Generated by Django 5.2.4 on 2025-11-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_position_calendaryeardata_positionx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Projekt'), ('to_produce', 'Do produkcji'), ('in_production', 'W produkcji'), ('done', 'Gotowy'), ('archived', 'Zarchiwizowany')], default='draft', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('production_note', models.TextField(blank=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='api.calendar')),
            ],
        ),
    ]
