# Generated by Django 5.2.4 on 2025-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_calendarproduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarproduction',
            name='status',
            field=models.CharField(choices=[('oczekujące', 'Oczekujące'), ('w trakcie', 'W Trakcie'), ('do druku', 'Gotowe do Druku'), ('gotowe', 'Gotowe'), ('odrzucony', 'Odrzucony')], default='oczekujące', max_length=50),
        ),
    ]
