# Generated by Django 5.2.4 on 2025-11-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_calendarproduction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarproduction',
            name='status',
            field=models.CharField(choices=[('draft', 'Projekt'), ('rejected', 'Odrzucony'), ('to_produce', 'Do produkcji'), ('in_production', 'W produkcji'), ('done', 'Gotowy'), ('archived', 'Zarchiwizowany')], default='draft', max_length=20),
        ),
    ]
