# Generated by Django 5.2.4 on 2025-11-30 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_calendarproduction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarproduction',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='api.calendar'),
        ),
    ]
