# Generated by Django 5.2.4 on 2026-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_calendarproduction_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmonthfieldtext',
            name='font_color',
            field=models.CharField(default='#000000', help_text='Np. #000000 lub rgba(...)', max_length=50),
        ),
        migrations.AddField(
            model_name='calendarmonthfieldtext',
            name='font_size',
            field=models.PositiveIntegerField(default=12, help_text='Rozmiar w px'),
        ),
    ]
