# Generated by Django 5.2.4 on 2026-01-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_calendarmonthfieldtext_font_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarmonthfieldtext',
            name='font_size',
        ),
    ]
