# Generated by Django 5.2.4 on 2026-01-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_calendarmonthfieldtext_font_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmonthfieldtext',
            old_name='font_color',
            new_name='color',
        ),
    ]
