# Generated by Django 5.2.4 on 2026-01-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_font_color_calendarmonthfieldtext_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmonthfieldtext',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
