# Generated by Django 5.2.4 on 2026-01-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_calendarmonthfieldtext_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atmosfera',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='calendartype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='detale',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='inspiracja',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='kolorystyka',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='kompozycja',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='perspektywa',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='realizm',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stylartystyczny',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stylnarracyjny',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tlo',
            options={'ordering': ['id']},
        ),
    ]
