# Generated by Django 5.2.4 on 2026-01-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_atmosfera_options_alter_calendartype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomgradient',
            name='strength',
        ),
    ]
