# Generated by Django 5.2.4 on 2026-02-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_bottomgradient_strength'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarType',
        ),
        migrations.RemoveField(
            model_name='outpaintingsdxl',
            name='input_image',
        ),
        migrations.RemoveField(
            model_name='upscaling',
            name='input_image',
        ),
        migrations.DeleteModel(
            name='ImageForField',
        ),
        migrations.DeleteModel(
            name='OutpaintingSDXL',
        ),
        migrations.DeleteModel(
            name='upscaling',
        ),
    ]
