# Generated by Django 5.2.4 on 2026-02-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_delete_calendartype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmosfera',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='detale',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='inspiracja',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='kolorystyka',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='kompozycja',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='perspektywa',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='realizm',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='stylartystyczny',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='stylnarracyjny',
            name='tlumaczenie',
        ),
        migrations.RemoveField(
            model_name='tlo',
            name='tlumaczenie',
        ),
        migrations.AlterField(
            model_name='calendarmonthfieldimage',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
